### ISSUE TITLE
Is this deprecated?

### ISSUE THREAD

**Issue by alanupstone** [aamplugin/aam-protected-media-files#5]
Not updated for a long time and not tested with the current WordPress version. Is it still supported? Or is it now part of AAM Plus package? Thanks. It does not appear to work with my installation of WordPress: 5.7.2.

**Comment by aamplugin** [comment]
Hello @alanupstone. Nope, the plugin is active and is used by a decent amount of users. Though, it is not part of Plus Package but rather an free extension for the core Advanced Access Manager plugin.
